name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: localazy/upload@v1

  dart-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          cache: true

      - name: "Run Flutter Analyze"
        run: flutter analyze

      - name: "Check Dart Formatting"
        run: dart format --set-exit-if-changed ./lib

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Preload Flutter artifacts
        run: flutter precache

      - name: "Install dependencies"
        run: flutter pub get

      - name: "Activate remove_from_coverage"
        run: flutter pub global activate remove_from_coverage

      - name: "Flutter Test"
        run: |
          flutter test --no-pub --coverage
          remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$'

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./**/coverage/lcov.info
